### ISSUE TITLE
Extracting a snippet with a string closing string lteral symbol at the end mangles the refactored let expression

### ISSUE THREAD

**Issue by 7sharp9** [dmannock/vscode-fsharp-refactor#1]
Silly example:
```
let str = types |> Array.map fsSig |> String.concat ", " 
```

highlight `types |> Array.map fsSig |> String.concat ", "`
extract let, results in:
```
let extracted = "types |> Array.map fsSig |> String.concat ", "
let str = " + extracted
```
Notice the opening string literal that should not be there

**Comment by dmannock** [comment]
Thanks for the report, I'll take a look.

Sorry for the delay, I didn't seen any notifications...although now I'm here i was expecting more reports (careful what I wish for).
