### ISSUE TITLE
Unnecessary brackets on inline

### ISSUE THREAD

**Issue by NicoleRauch** [dmannock/vscode-fsharp-refactor#3]
On inline I get brackets around the expression even when they are not necessary. Maybe the code generator for the inlining can be improved along these lines?

To give you an example: I extracted the list element from `[a.b]`, and after inlining I ended up with `[(a.b)]`. While I can see that the brackets might be necessary in some cases when inlining this expression, they are not in this case.

**Comment by dmannock** [comment]
hi,
Thanks for this, inlining expressions isn't aware of context but a first pass (to follow) at improving it will close this issue as it stands.
