### ISSUE TITLE
Empty line prevents inlining

### ISSUE THREAD

**Issue by NicoleRauch** [dmannock/vscode-fsharp-refactor#4]
I found an issue with inlining. Here is a sample snippet:

```
module M

open Expecto
open Expecto.Expect

let tests =
    testList "X" [

        test "Y" {
            let expectedEvents = []

            equal [] expectedEvents ""
        }
    ]
```

I cannot inline the _expectedEvents_ let-binding, but if I remove the empty line between the definition and its usage, I can inline it.

**Comment by dmannock** [comment]
Thanks for the reports, I'll take a look.

If you happen to find anything else please give me a shout (especially since you're testing on a mac) :)

**Comment by NicoleRauch** [comment]
Thanks for the quick fix! New bug report incoming... ;-)
